import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { LanguageModeContextProvider } from "@/contexts/LanguageModeContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} p-0 m-0 box-border overflow-x-hidden`}
      >
        <LanguageModeContextProvider>
          <Navbar />
          {children}
        </LanguageModeContextProvider>
      </body>
    </html>
  );
}
