"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ThemeProvider, createTheme } from "@mui/material";
import Navbar from "@/components/Navbar/Navbar";
import { LanguageModeContextProvider } from "@/contexts/LanguageModeContext";
import { MuiSetup } from "@/styles/muiThemeSetup";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = createTheme(MuiSetup);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} h-screen p-0 m-0 box-border`}>
        <ThemeProvider theme={theme}>
          <LanguageModeContextProvider>
            <Navbar />
            {children}
          </LanguageModeContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
